//####################################################################
//constantes para BITACORA
//EQUIPO DE RED
export const EQUIPO_RED_CREATE_REQUEST = 'EQUIPO_RED_CREATE_REQUEST'
export const EQUIPO_RED_CREATE_SUCCESS = 'EQUIPO_RED_CREATE_SUCCESS'
export const EQUIPO_RED_CREATE_FAIL = 'EQUIPO_RED_CREATE_FAIL'


export const EQUIPO_RED_LIST_REQUEST = 'EQUIPO_RED_LIST_REQUEST'
export const EQUIPO_RED_LIST_SUCCESS = 'EQUIPO_RED_LIST_SUCCESS'
export const EQUIPO_RED_LIST_FAIL = 'EQUIPO_RED_LIST_FAIL'

//MANTENIMIENTO EQUIPO
export const MANTENIMIENTO_EQUIPO_CREATE_REQUEST = 'MANTENIMIENTO_EQUIPO_CREATE_REQUEST'
export const MANTENIMIENTO_EQUIPO_CREATE_SUCCESS = 'MANTENIMIENTO_EQUIPO_CREATE_SUCCESS'
export const MANTENIMIENTO_EQUIPO_CREATE_FAIL = 'MANTENIMIENTO_EQUIPO_CREATE_FAIL'

export const MANTENIMIENTO_EQUIPO_LIST_REQUEST = 'MANTENIMIENTO_EQUIPO_LIST_REQUEST'
export const MANTENIMIENTO_EQUIPO_LIST_SUCCESS = 'MANTENIMIENTO_EQUIPO_LIST_SUCCESS'
export const MANTENIMIENTO_EQUIPO_LIST_FAIL = 'MANTENIMIENTO_EQUIPO_LIST_FAIL'

//MOVIMIENTO EQUIPO
export const MOVIMIENTO_EQUIPO_CREATE_REQUEST = 'MOVIMIENTO_EQUIPO_CREATE_REQUEST'
export const MOVIMIENTO_EQUIPO_CREATE_SUCCESS = 'MOVIMIENTO_EQUIPO_CREATE_SUCCESS'
export const MOVIMIENTO_EQUIPO_CREATE_FAIL = 'MOVIMIENTO_EQUIPO_CREATE_FAIL'

export const MOVIMIENTO_EQUIPO_LIST_REQUEST = 'MOVIMIENTO_EQUIPO_LIST_REQUEST'
export const MOVIMIENTO_EQUIPO_LIST_SUCCESS = 'MOVIMIENTO_EQUIPO_LIST_SUCCESS'
export const MOVIMIENTO_EQUIPO_LIST_FAIL = 'MOVIMIENTO_EQUIPO_LIST_FAIL'


