//####################################################################
//constantes para BITACORA EQUIPOS
//EQUIPO DE RED
export const EQUIPO_RED_CREATE_REQUEST = 'EQUIPO_RED_CREATE_REQUEST'
export const EQUIPO_RED_CREATE_SUCCESS = 'EQUIPO_RED_CREATE_SUCCESS'
export const EQUIPO_RED_CREATE_FAIL = 'EQUIPO_RED_CREATE_FAIL'


export const EQUIPO_RED_LIST_REQUEST = 'EQUIPO_RED_LIST_REQUEST'
export const EQUIPO_RED_LIST_SUCCESS = 'EQUIPO_RED_LIST_SUCCESS'
export const EQUIPO_RED_LIST_FAIL = 'EQUIPO_RED_LIST_FAIL'

//MANTENIMIENTO EQUIPO
export const MANTENIMIENTO_EQUIPO_CREATE_REQUEST = 'MANTENIMIENTO_EQUIPO_CREATE_REQUEST'
export const MANTENIMIENTO_EQUIPO_CREATE_SUCCESS = 'MANTENIMIENTO_EQUIPO_CREATE_SUCCESS'
export const MANTENIMIENTO_EQUIPO_CREATE_FAIL = 'MANTENIMIENTO_EQUIPO_CREATE_FAIL'

export const MANTENIMIENTO_EQUIPO_LIST_REQUEST = 'MANTENIMIENTO_EQUIPO_LIST_REQUEST'
export const MANTENIMIENTO_EQUIPO_LIST_SUCCESS = 'MANTENIMIENTO_EQUIPO_LIST_SUCCESS'
export const MANTENIMIENTO_EQUIPO_LIST_FAIL = 'MANTENIMIENTO_EQUIPO_LIST_FAIL'

//MOVIMIENTO EQUIPO
export const MOVIMIENTO_EQUIPO_CREATE_REQUEST = 'MOVIMIENTO_EQUIPO_CREATE_REQUEST'
export const MOVIMIENTO_EQUIPO_CREATE_SUCCESS = 'MOVIMIENTO_EQUIPO_CREATE_SUCCESS'
export const MOVIMIENTO_EQUIPO_CREATE_FAIL = 'MOVIMIENTO_EQUIPO_CREATE_FAIL'

export const MOVIMIENTO_EQUIPO_LIST_REQUEST = 'MOVIMIENTO_EQUIPO_LIST_REQUEST'
export const MOVIMIENTO_EQUIPO_LIST_SUCCESS = 'MOVIMIENTO_EQUIPO_LIST_SUCCESS'
export const MOVIMIENTO_EQUIPO_LIST_FAIL = 'MOVIMIENTO_EQUIPO_LIST_FAIL'


//#######################################
//constantes para BITACORA fIBRA
//Trazado fibra
export const TRAZADO_FIBRA_CREATE_REQUEST = 'TRAZADO_FIBRA_CREATE_REQUEST'
export const TRAZADO_FIBRA_CREATE_SUCCESS = 'TRAZADO_FIBRA_CREATE_SUCCESS'
export const TRAZADO_FIBRA_CREATE_FAIL = 'TRAZADO_FIBRA_CREATE_FAIL'

export const TRAZADO_FIBRA_LIST_REQUEST = 'TRAZADO_FIBRA_LIST_REQUEST'
export const TRAZADO_FIBRA_LIST_SUCCESS = 'TRAZADO_FIBRA_LIST_SUCCESS'
export const TRAZADO_FIBRA_LIST_FAIL = 'TRAZADO_FIBRA_LIST_FAIL'

//trabajos fibra
export const TRABAJOS_FIBRA_CREATE_REQUEST = 'TRABAJOS_FIBRA_CREATE_REQUEST'
export const TRABAJOS_FIBRA_CREATE_SUCCESS = 'TRABAJOS_FIBRA_CREATE_SUCCESS'
export const TRABAJOS_FIBRA_CREATE_FAIL = 'TRABAJOS_FIBRA_CREATE_FAIL'

export const TRABAJOS_FIBRA_LIST_REQUEST = 'TRABAJOS_FIBRA_LIST_REQUEST'
export const TRABAJOS_FIBRA_LIST_SUCCESS = 'TRABAJOS_FIBRA_LIST_SUCCESS'
export const TRABAJOS_FIBRA_LIST_FAIL = 'TRABAJOS_FIBRA_LIST_FAIL'

//TIPO FIBRA
export const TIPOS_FIBRA_LIST_REQUEST = 'TIPOS_FIBRA_LIST_REQUEST'
export const TIPOS_FIBRA_LIST_SUCCESS = 'TIPOS_FIBRA_LIST_SUCCESS'
export const TIPOS_FIBRA_LIST_FAIL = 'TIPOS_FIBRA_LIST_FAIL'

//TIPO TRABAJO
export const TIPOS_TRABAJOS_LIST_REQUEST = 'TIPOS_TRABAJOS_LIST_REQUEST'
export const TIPOS_TRABAJOS_LIST_SUCCESS = 'TIPOS_TRABAJOS_LIST_SUCCESS'
export const TIPOS_TRABAJOS_LIST_FAIL = 'TIPOS_TRABAJOS_LIST_FAIL'





