export const CLIENTE_LIST_REQUEST = 'BLOG_LIST_REQUEST'
export const CLIENTE_LIST_SUCCESS = 'BLOG_LIST_SUCCESS'
export const CLIENTE_LIST_FAIL = 'BLOG_LIST_FAIL'
export const CLIENTE_LIST_RESET = 'BLOG_LIST_RESET'

export const BLOG_DETAILS_REQUEST = 'BLOG_DETAILS_REQUEST'
export const BLOG_DETAILS_SUCCESS = 'BLOG_DETAILS_SUCCESS'
export const BLOG_DETAILS_FAIL = 'BLOG_DETAILS_FAIL'

export const CLIENTE_DELETE_REQUEST = 'CLIENTE_DELETE_REQUEST'
export const CLIENTE_DELETE_SUCCESS = 'CLIENTE_DELETE_SUCCESS'
export const CLIENTE_DELETE_FAIL = 'CLIENTE_DELETE_FAIL'

export const CLIENTE_CREATE_REQUEST = 'CLIENTE_CREATE_REQUEST'
export const CLIENTE_CREATE_SUCCESS = 'CLIENTE_CREATE_SUCCESS'
export const CLIENTE_CREATE_FAIL = 'CLIENTE_CREATE_FAIL'

export const CLIENTE_UPDATE_REQUEST = 'CLIENTE_UPDATE_REQUEST'
export const CLIENTE_UPDATE_SUCCESS = 'CLIENTE_UPDATE_SUCCESS'
export const CLIENTE_UPDATE_FAIL = 'CLIENTE_UPDATE_FAIL'
export const CLIENTE_UPDATE_RESET = 'CLIENTE_UPDATE_RESET'


