export const FACTURA_VENTA_CREATE_REQUEST = 'FACTURA_VENTA_CREATE_REQUEST'
export const FACTURA_VENTA_CREATE_SUCCESS = 'FACTURA_VENTA_CREATE_SUCCESS'
export const FACTURA_VENTA_CREATE_FAIL = 'FACTURA_VENTA_CREATE_FAIL'

export const FACTURA_VENTA_LIST_REQUEST = 'FACTURA_VENTA_LIST_REQUEST'
export const FACTURA_VENTA_LIST_SUCCESS = 'FACTURA_VENTA_LIST_SUCCESS'
export const FACTURA_VENTA_LIST_FAIL = 'FACTURA_VENTA_LIST_FAIL'


export const FACTURA_VENTA_UNICA_REQUEST = 'FACTURA_VENTA_UNICA_REQUEST'
export const FACTURA_VENTA_UNICA_SUCCESS = 'FACTURA_VENTA_UNICA_SUCCESS'
export const FACTURA_VENTA_UNICA_FAIL = 'FACTURA_VENTA_UNICA_FAIL'


export const FACTURA_VENTA_DELETE_REQUEST = 'FACTURA_VENTA_DELETE_REQUEST'
export const FACTURA_VENTA_DELETE_SUCCESS = 'FACTURA_VENTA_DELETE_SUCCESS'
export const FACTURA_VENTA_DELETE_FAIL = 'FACTURA_VENTA_DELETE_FAIL'



// para actualizar el monto pendiente cada vez que se realice un pago
export const FACTURA_VENTA_UPDATE_REQUEST = 'FACTURA_VENTA_UPDATE_REQUEST'
export const FACTURA_VENTA_UPDATE_SUCCESS = 'FACTURA_VENTA_UPDATE_SUCCESS'
export const FACTURA_VENTA_UPDATE_FAIL = 'FACTURA_VENTA_UPDATE_FAIL'
export const FACTURA_VENTA_UPDATE_RESET = 'FACTURA_VENTA_UPDATE_RESET'



//DETALLE DE FACTURAS
export const FACTURA_DETALLE_VENTA_CREATE_REQUEST = 'FACTURA_DETALLE_VENTA_CREATE_REQUEST'
export const FACTURA_DETALLE_VENTA_CREATE_SUCCESS = 'FACTURA_DETALLE_VENTA_CREATE_SUCCESS'
export const FACTURA_DETALLE_VENTA_CREATE_FAIL = 'FACTURA_DETALLE_VENTA_CREATE_FAIL'

export const FACTURA_SOLA_DETALLE_VENTA_REQUEST = 'FACTURA_SOLA_DETALLE_VENTA_REQUEST'
export const FACTURA_SOLA_DETALLE_VENTA_SUCCESS = 'FACTURA_SOLA_DETALLE_VENTA_SUCCESS'
export const FACTURA_SOLA_DETALLE_VENTA_FAIL = 'FACTURA_SOLA_DETALLE_VENTA_FAIL'

