export const FACTURA_VENTA_LIST_REQUEST = 'FACTURA_VENTA_LIST_REQUEST'
export const FACTURA_VENTA_LIST_SUCCESS = 'FACTURA_VENTA_LIST_SUCCESS'
export const FACTURA_VENTA_LIST_FAIL = 'FACTURA_VENTA_LIST_FAIL'
export const FACTURA_VENTA_LIST_RESET = 'FACTURA_VENTA_LIST_RESET'

export const FACTURA_VENTA_DELETE_REQUEST = 'FACTURA_VENTA_DELETE_REQUEST'
export const FACTURA_VENTA_DELETE_SUCCESS = 'FACTURA_VENTA_DELETE_SUCCESS'
export const FACTURA_VENTA_DELETE_FAIL = 'FACTURA_VENTA_DELETE_FAIL'

export const FACTURA_VENTA_CREATE_REQUEST = 'FACTURA_VENTA_CREATE_REQUEST'
export const FACTURA_VENTA_CREATE_SUCCESS = 'FACTURA_VENTA_CREATE_SUCCESS'
export const FACTURA_VENTA_CREATE_FAIL = 'FACTURA_VENTA_CREATE_FAIL'



