//Empresa_corp
export const EMPRESA_CORP_LIST_REQUEST = 'EMPRESA_CORP_LIST_REQUEST'
export const EMPRESA_CORP_LIST_SUCCESS = 'EMPRESA_CORP_LIST_SUCCESS'
export const EMPRESA_CORP_LIST_FAIL = 'EMPRESA_CORP_LIST_FAIL'
export const EMPRESA_CORP_LIST_RESET = 'EMPRESA_CORP_LIST_RESET'

// Caja_empresa
export const CAJA_EMPRESA_LIST_REQUEST = 'CAJA_CORP_LIST_REQUEST'
export const CAJA_EMPRESA_LIST_SUCCESS = 'CAJA_CORP_LIST_SUCCESS'
export const CAJA_EMPRESA_LIST_FAIL = 'CAJA_CORP_LIST_FAIL'
export const CAJA_EMPRESA_LIST_RESET = 'CAJA_CORP_LIST_RESET'

//Modo_CompraVenta
export const MODO_CV_LIST_REQUEST = 'MODO_CV_LIST_REQUEST'
export const MODO_CV_LIST_SUCCESS = 'MODO_CV_LIST_SUCCESS'
export const MODO_CV_LIST_FAIL = 'MODO_CV_LIST_FAIL'
export const MODO_CV_LIST_RESET = 'MODO_CV_LIST_RESET'

//Bodega
export const BODEGA_LIST_REQUEST = 'BODEGA_LIST_REQUEST'
export const BODEGA_LIST_SUCCESS = 'BODEGA_LIST_SUCCESS'
export const BODEGA_LIST_FAIL = 'BODEGA_LIST_FAIL'
export const BODEGA_LIST_RESET = 'BODEGA_LIST_RESET'


