
export const PRODUCTO_CREATE_REQUEST = 'PRODUCTO_CREATE_REQUEST'
export const PRODUCTO_CREATE_SUCCESS = 'PRODUCTO_CREATE_SUCCESS'
export const PRODUCTO_CREATE_FAIL = 'PRODUCTO_CREATE_FAIL'

export const TIPO_PRODUCTO_LIST_REQUEST = 'TIPO_PRODUCTO_LIST_REQUEST'
export const TIPO_PRODUCTO_LIST_SUCCESS = 'TIPO_PRODUCTO_LIST_SUCCESS'
export const TIPO_PRODUCTO_LIST_FAIL = 'TIPO_PRODUCTO_LIST_FAIL'
export const TIPO_PRODUCTO_LIST_RESET = 'TIPO_PRODUCTO_LIST_RESET'

export const SUBTIPO_PRODUCTO_LIST_REQUEST = 'SUBTIPO_PRODUCTO_LIST_REQUEST'
export const SUBTIPO_PRODUCTO_LIST_SUCCESS = 'SUBTIPO_PRODUCTO_LIST_SUCCESS'
export const SUBTIPO_PRODUCTO_LIST_FAIL = 'SUBTIPO_PRODUCTO_LIST_FAIL'
export const SUBTIPO_PRODUCTO_LIST_RESET = 'SUBTIPO_PRODUCTO_LIST_RESET'

export const ESTADO_PRODUCTO_LIST_REQUEST = 'ESTADO_PRODUCTO_LIST_REQUEST'
export const ESTADO_PRODUCTO_LIST_SUCCESS = 'ESTADO_PRODUCTO_LIST_SUCCESS'
export const ESTADO_PRODUCTO_LIST_FAIL = 'ESTADO_PRODUCTO_LIST_FAIL'
export const ESTADO_PRODUCTO_LIST_RESET = 'ESTADO_PRODUCTO_LIST_RESET'

